language: node_js
node_js:
  - "8"
  - "10"
  - "node"
sudo: false
install:
  - npm install
  - npm run fetch-test-suite
script:
  - npm run test
notifications:
  email:
    on_success: change
    on_failure: change
